service: testLambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: index.js
    events:
      - httpApi:
          path: /default/testFunction
          method: post
